WayawayaGach/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

WayawayaGacha/urls.py
from django.contrib import admin
from django.urls import path, include
from menu import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.top_page),
    path('gacha/', include('gacha.urls')),
    path('menu/', include('menu.urls')),
]

gacha/urls.py
from django.urls import path
from . import views

app_name = 'gacha'

urlpatterns = [
    path('', views.gacha, name='gacha'),
    # path('complate/<int:id>/', views.market_complate, ),
    # path('result/', views.market_search_result, name='searchResult'),
    # path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    # path('<slug:c_slug>/<slug:sc_slug>', views.allProdCat, name='products_by_subcategory'),
    # path('<slug:c_slug>/<slug:sc_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu_list, ),
    # path('complate/<int:id>/', views.market_complate, ),
    # path('result/', views.market_search_result, name='searchResult'),
    # path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    # path('<slug:c_slug>/<slug:sc_slug>', views.allProdCat, name='products_by_subcategory'),
    # path('<slug:c_slug>/<slug:sc_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
]

menu/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='カテゴリ')
    slug = models.SlugField(max_length=250, unique=True, primary_key=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'カテゴリ'
        verbose_name_plural = 'カテゴリ'

    def __str__(self):
        return '{}'.format(self.name)
    
    
class SubCategory(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='サブカテゴリ')
    slug = models.SlugField(max_length=250, unique=True, primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='カテゴリ')

    class Meta:
        ordering = ('name',)
        verbose_name = 'サブカテゴリ'
        verbose_name_plural = 'サブカテゴリ'

    def __str__(self):
        return '{}'.format(self.name)


class Menu(models.Model):
    name = models.CharField(max_length=250, unique=False, verbose_name='名前')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='カテゴリ')
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, verbose_name='サブカテゴリ')
    image = models.ImageField(upload_to='menu', blank=False)
    price = models.IntegerField(blank=True, verbose_name='値段')
    available = models.BooleanField(default=True, verbose_name='公開')
    

    class Meta:
        db_table = 'menu'
        ordering = ('name',)
        verbose_name = 'メニュー'
        verbose_name_plural = 'メニュー'

    
    def __str__(self):
        return '{}'.format(self.name)

gacha/forms.py
from django import forms


class BudgetInputForm():
    budget = forms.IntegerField(initial='3000')

gacha/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import BudgetInputForm


def gacha(request):
    if request.method == 'POST':
        form = BudgetInputForm(request.POST)
        if form.is_valid():
            form.save()
            
        return render(request, 'gacha/gacha.html', {"form": form})
    else:
        form = BudgetInputForm()
        return render(request, 'gacha/gacha.html', {"form": form})

menu/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse


def top_page(request):
    return render(request,'menu/top.html',)


def menu_list(request):
    return render(request, 'menu/menu_list.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/gacha/gacha.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
わやわやガチャ - ガチャ
{% endblock %}
{% block title %}
わやわやガチャ - ガチャ画面
{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col side-area">

        </div>

        <div class="col main-area">
            <div class="gacha-result">
                <div class="item-card">
                    <h2 class="menu-name">殿の唐揚げ</h2>
                    <p>400円</p>
                </div>
            </div>
            <div class="gacha-container">
                テスト
                <form class="row g-3" action="{% url 'gacha:gacha' %}" method="get">
                    {% csrf_token %}
                    <div class="col-auto">
                        <input class="form-control" type="number" aria-label="budget" name="budget">
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-3">ガチャを回す</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col side-area">

        </div>
    </div>
</div>







{% endblock %}

templates/menu/menu_list.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
わやわやガチャ - メニュー一覧
{% endblock %}
{% block title %}
わやわやガチャ - メニュー一覧
{% endblock %}
{% block content %}

<div class="sample">
    テスト
</div>




{% endblock %}

templates/menu/top.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
    わやわやガチャ - トップ
{% endblock %}
{% block title %}
    わやわやガチャ - トップ
{% endblock %}
{% block content %}

<div>
    ここはトップページです
</div>

{% endblock %}

templates/navbar.html
{% block content %}

{% endblock %}